'use client';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter, useParams } from 'next/navigation';
import { FaArrowLeft, FaFloppyDisk } from 'react-icons/fa6';
import { adminProjectsAPI, adminProgramsAPI } from '@/lib/admin/api';
import toast from 'react-hot-toast';

export default function EditProjectPage() {
  const router = useRouter(); const { id } = useParams(); const [loading, setLoading] = useState(false); const [programs, setPrograms] = useState<any[]>([]); const [form, setForm] = useState<any>(null);
  useEffect(() => { adminProgramsAPI.getAll().then(data => setPrograms(Array.isArray(data) ? data : [])); if (id) adminProjectsAPI.getOne(Number(id)).then(setForm).catch(() => router.push('/admin/projects')); }, [id]);
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); try { await adminProjectsAPI.update(Number(id), {...form, program_id: Number(form.program_id)}); toast.success('تم التحديث'); router.push('/admin/projects'); } catch { toast.error('فشل التحديث'); } finally { setLoading(false); } };
  if (!form) return <div className="pt-navbar min-h-screen flex items-center justify-center"><div className="w-12 h-12 border-4 border-primary-500 border-t-transparent rounded-full animate-spin" /></div>;
  return (<div className="pt-navbar container-page max-w-4xl mx-auto min-h-screen"><div className="flex items-center gap-4 mb-8"><Link href="/admin/projects" className="p-2 hover:bg-gray-100 rounded-lg"><FaArrowLeft /></Link><h1 className="text-3xl font-bold">تعديل مشروع</h1></div><form onSubmit={handleSubmit} className="card space-y-6"><div><label className="block mb-2">العنوان (عربي) *</label><input type="text" value={form.title_ar || ''} onChange={e => setForm({...form, title_ar: e.target.value})} className="w-full p-3 border rounded-xl" required /></div><div><label>العنوان (إنجليزي)</label><input type="text" value={form.title || ''} onChange={e => setForm({...form, title: e.target.value})} className="w-full p-3 border rounded-xl" /></div><div><label>الوصف</label><textarea value={form.description || ''} onChange={e => setForm({...form, description: e.target.value})} rows={4} className="w-full p-3 border rounded-xl" /></div><div><label>البرنامج *</label><select value={form.program_id || ''} onChange={e => setForm({...form, program_id: e.target.value})} className="w-full p-3 border rounded-xl" required><option value="">اختر البرنامج</option>{programs.map(p => <option key={p.id} value={p.id}>{p.name_ar}</option>)}</select></div><div className="grid grid-cols-2 gap-4"><div><label>الحالة</label><select value={form.status || 'active'} onChange={e => setForm({...form, status: e.target.value})} className="w-full p-3 border rounded-xl"><option value="active">نشط</option><option value="completed">مكتمل</option></select></div><div><label>عدد المستفيدين</label><input type="number" value={form.beneficiaries || 0} onChange={e => setForm({...form, beneficiaries: +e.target.value})} className="w-full p-3 border rounded-xl" /></div></div><div><label>الموقع</label><input type="text" value={form.location || ''} onChange={e => setForm({...form, location: e.target.value})} className="w-full p-3 border rounded-xl" /></div><div className="flex gap-4 pt-4"><button type="submit" disabled={loading} className="btn btn-primary"><FaFloppyDisk /> {loading ? 'جاري الحفظ...' : 'تحديث'}</button><Link href="/admin/projects" className="btn bg-gray-200 text-gray-700">إلغاء</Link></div></form></div>);
}
